### ISSUE TITLE
Missing Api Put

### ISSUE THREAD

**Issue by xrobert35** [olivierlsc/swagger-express-ts#1]
Hello, 

Perhaps i'm missing something but it look like you are not exporting the "put" api in the index.ts

`export { IApiOperationPutArgs, ApiOperationPut } from "./api-operation-put.decorator";`

I was about to make the same library but your saved me some days of work :) thanks for this :)

**Comment by olivierlsc** [comment]
Hi @xrobert35 ,

Nice that this lib serve you.

Sorry it was an oversight on my part. Now, GET, POST, PUT, PATCH and DELETE are available in version 1.0.0-alpha.5.

**Comment by olivierlsc** [comment]
Hi @xrobert35 ,

I am looking for collaborators to enrich this library. Would you be interested to work with me? If so, I thank you for contacting me on linkedin.

Thanks.
