### ISSUE TITLE
@ApiModelProperty gives error

### ISSUE THREAD

**Issue by haroon407** [olivierlsc/swagger-express-ts#13]
Hi,
Whenever I attach the @ApiModelProperty it gives me an error stating cannot access name attribute of undefined. The error appears in the following line so I just commented it and it worked. But can you please look into it?

var propertyType = Reflect.getMetadata("design:type", target, propertyKey).name.toLowerCase();

**Comment by haroon407** [comment]
Here's a short example of my model:

@ApiModel({
    name: "Candidate",
    description: "Inherits from Company"
})
export class CandidateClass extends CompanyClass {
    @ApiModelProperty({ required: false })
    startup_probability = Number;
    @ApiModelProperty({ required: false })
    url_recheck_on = Date;
    @ApiModelProperty({ required: false })
    url_recheck_errors = Number;
    @ApiModelProperty({ required: false })
    url_identification_postponed_until = Date;
    @ApiModelProperty({ required: false })
    status = String;
}

**Comment by xrobert35** [comment]
Do you have the instruction : 
import 'reflect-metadata';   

at the begining of your application ?  (package.json  dependencie : "reflect-metadata": "^0.1.10")

**Comment by olivierlsc** [comment]
Can you test with :

@apimodel({
name: "Candidate",
description: "Inherits from Company"
})
export class CandidateClass extends CompanyClass {
@apimodelproperty({ required: false })
startup_probability : number;
@apimodelproperty({ required: false })
url_recheck_on : string; // swagger does not know the type Date. https://swagger.io/docs/specification/data-models/data-types/
@apimodelproperty({ required: false })
url_recheck_errors : number;
@apimodelproperty({ required: false })
url_identification_postponed_until : string;
@apimodelproperty({ required: false })
status : string;
}

**Comment by haroon407** [comment]
Hi, Thanks a lot for all the help and responses :) . @xrobert35 yup I have "reflect-metadata": "^0.1.12" in the package.json.
@olivierlsc I tried  it by using the swagger's compliant datatypes but still the error persists :(

/Users/***/backend/node_modules/swagger-express-ts/dist/api-model-property.decorator.js:7
        var propertyType = Reflect.getMetadata("design:type", target, propertyKey).name.toLowerCase();
                                                                                  ^

TypeError: Cannot read property 'name' of undefined

**Comment by xrobert35** [comment]
@haroon407,

I tried with your class on a basic project and I dont get any error.

Something is strange about your log, it told you the problem is on line 7  but line 7 is this one for me :

`swagger_service_1.SwaggerService.getInstance().addApiModelProperty(args, target, propertyKey, propertyType);`

Be sure to have the lastest version (check the package.json of your node module). And if you can try to add breakpoint on the line, your could perhaps told us which propertyKey fail

Thanks

**Comment by fatfatson** [comment]
same problem!
`Reflect.getMetadata("design:type", target, propertyKey)` returns undefined, so I get a 
```
TypeError: Cannot read property 'name' of undefined
```

**Comment by fatfatson** [comment]
got it,
should add 
`"emitDecoratorMetadata": true,`
to tsconfig

**Comment by xrobert35** [comment]
Ah thanks  @fatfatson,

@olivierlsc  perhaps you can add this in the readme ?

**Comment by olivierlsc** [comment]
Thanks @fatfatson.

@xrobert35, I will add this in the readme.

**Comment by davidsoderberg** [comment]
I have done all that have been suggested in this issue but no success :( .

**Comment by cardnetwork** [comment]
Can we please reopen this issue. My team is experiencing this as well, but only on a single case. This appears to be happening when you have circular definitions, so A and B are ApiModels() and A has a B type field and B has an  A type field.
