### ISSUE TITLE
How to set responses just return string

### ISSUE THREAD

**Issue by zerox12311** [olivierlsc/swagger-express-ts#26]
I have one api just return a plain string, I don't want to return all Model.
I don't know how to set response to return a plain string.

**Comment by olivierlsc** [comment]
Hi @zerox12311 ,

You can add parameter produces in Api Operation.
Example:
`
@ApiOperationGet({
    description: "Get versions objects list",
    summary: "Get versions list",
    responses: {
      200: {
        type: SwaggerDefinitionConstant.Response.Type.STRING
      }
    },
    produces: [
      SwaggerDefinitionConstant.Produce.JSON,
      SwaggerDefinitionConstant.Produce.TEXT_PLAIN
    ]
  })
  @httpGet("/")
  public getVersions(
    request: express.Request,
    response: express.Response,
    next: express.NextFunction
  ): void {
    response.send("My text");
  }
`

I hope this will help you.

**Comment by zerox12311** [comment]
Thank you!!!

**Comment by olivierlsc** [comment]
I close this issue.
