### ISSUE TITLE
ApiModelProperty - Example property

### ISSUE THREAD

**Issue by LednevEugene** [olivierlsc/swagger-express-ts#37]
Hello!
Currently (v. 1.0.1), `IApiModelPropertyArgs` interface has a property `example` like
`example?: any[];`
In this case I have no option to set example values like `string` of `object`. So UI part will show `array` always. 
It would be great to change type of `example` property to `any` or `string | object | []` or something like this.

Thanks in advance!

**Comment by markmblc** [comment]
Cast example value to any as a workaround:

```
@ApiModelProperty({
    description: 'Description of document',
    example: 'Unit 1234 facility contract' as any
  })

 @ApiModelProperty({
    description: 'Object containing implementation specific metadata',
    example: {
      "unit": "1234",
      "docType": "contract",
      "unitType": "facility"
    } as any
```

**Comment by LednevEugene** [comment]
Thanks @markmblc !
