### ISSUE TITLE
Can I reference a JSON Schema directly and use it as a model?

### ISSUE THREAD

**Issue by XanderEmu** [olivierlsc/swagger-express-ts#42]
Can I reference a JSON Schema directly and use it as a model?

**Comment by Sukh-vip3r** [comment]
@olivierlsc please help if you can ??

**Comment by olivierlsc** [comment]
You can define models in a JSON format like [here](https://github.com/olivierlsc/swagger-express-ts/blob/master/wiki/configuration.md)

**Comment by Sukh-vip3r** [comment]
How will i set example response as json ?
`  responses: {

            200: {
                description: "Success",
                type: SwaggerDefinitionConstant.Response.Type.OBJECT,
                model: 'Some'
            }
        },`
How to do this if i have to send a json as example ?

**Comment by olivierlsc** [comment]
`
app.use( swagger.express({
    definition : {
        ...
        models : {
            Some: {
                properties : {
                    id : {
                        type : SwaggerDefinitionConstant.Model.Property.Type.STRING ,
                        required : true
                    } ,
                    ...
                }
            }
        } ,
        ...
    }
}) );
`

**Comment by XanderEmu** [comment]
Not exactly what I meant but I guess it could work, too.

**Comment by Sukh-vip3r** [comment]
i want example response like this 

{
"statusCode":200,
"message":"Success",
"data":{
"usersCounts":71,
"ongoingCounts":0,
"todayEarning":0,
"todayCommission":0
}
}

**Comment by olivierlsc** [comment]
Here an example :

```
app.use( swagger.express({
    definition : {
		...
        models : {
			UserData: {
				usersCounts: {
					type : SwaggerDefinitionConstant.Model.Property.Type.NUMBER
				},
				ongoingCounts: {
					type : SwaggerDefinitionConstant.Model.Property.Type.NUMBER
				},
				todayEarning: {
					type : SwaggerDefinitionConstant.Model.Property.Type.NUMBER
				},
				todayCommission: {
					type : SwaggerDefinitionConstant.Model.Property.Type.NUMBER
				}
			},
            JsonUser : {
                properties : {
                    statusCode: {
                        type : SwaggerDefinitionConstant.Model.Property.Type.STRING
                    } ,
                    message:{
						type : SwaggerDefinitionConstant.Model.Property.Type.STRING
					},
					data: {
						type: SwaggerDefinitionConstant.Model.Property.Type.OBJECT,
						model: 'UserData'
					}
       
                }
            }
        } ,
		...
    }
}) );
```

**Comment by Sukh-vip3r** [comment]
thanks @olivierlsc . but how to nest the models ??

**Comment by olivierlsc** [comment]
@Sukh-vip3r , you can nest the models like this :

```
app.use( swagger.express({
    definition : {
		...
        models : {
			Car: {
				properties : {
					name: {
						type : SwaggerDefinitionConstant.Model.Property.Type.STRING
					},
					author: {
						type : SwaggerDefinitionConstant.Model.Property.Type.OBJECT,
						model: 'Author'
					}
				}
			},
            Author : {
                properties : {
                    name: {
                        type : SwaggerDefinitionConstant.Model.Property.Type.STRING
                    }
                }
            }
        } ,
		...
    }
}) );
```

**Comment by Sukh-vip3r** [comment]
Thank you so much for your help @olivierlsc .
