### ISSUE TITLE
Array of complex types not working

### ISSUE THREAD

**Issue by TomWebbio** [olivierlsc/swagger-express-ts#45]
Hi,

I'm using the following code to document an array of a complex type, but swagger isn't generating the documentation properly.

  @ApiModelProperty({
    description: "Wordpress modules available on this page",
    required: true
  })
  public wordpressPostModules: WordPressModule[];

It gives an error unknown for the type of array and has a loading icon when I try and look at the documentation. 
WordPressModule is a seperate class that does show up properly in the models section. When I add it as a single property, not an array, it works fine.

Am I missing something here?

**Comment by eyalmt** [comment]
Typescript reflection cannot infer the exact type of array properties, so you need to help it.  
Just add the model name to the array model property like so:

@ApiModelProperty({  
&nbsp;&nbsp;&nbsp;&nbsp;    description: "Wordpress modules available on this page",  
&nbsp;&nbsp;&nbsp;&nbsp;    model: "WordPressModule",  
&nbsp;&nbsp;&nbsp;&nbsp;    required: true  
})  
public wordpressPostModules: WordPressModule[];

**Comment by WeekendMan** [comment]
Response is incorrect, this syntax defines type as `Model` but it should be `Model[]`
