### ISSUE TITLE
Support header params in IApiOperationArgsBaseParameters

### ISSUE THREAD

**Issue by kibertoad** [olivierlsc/swagger-express-ts#54]
Currently only `path`, `query`, `body` and `formData` are valid options, but Swagger also supports Header parameter: `https://swagger.io/docs/specification/2-0/describing-parameters/#header-parameters`

**Comment by hoangpham95** [comment]
I also love this to be supported as well

**Comment by thinkingmik** [comment]
I pushed a pull request for this feature #64

**Comment by thinkingmik** [comment]
The new release v1.1.0 accepts headers params
