### ISSUE TITLE
Array of items in query

### ISSUE THREAD

**Issue by kitsoRik** [olivierlsc/swagger-express-ts#68]
Hi, I'm using your package for project, but it has a problem that stopped me. I can't use array in query instead of it I see `error` in browser console `TypeError: Cannot read property 'anyOf' of undefined`. 

I found, it because `buildParameters` doesn't assign items to native swagger parameter.

I already fixed it in PR https://github.com/olivierlsc/swagger-express-ts/pull/69.

![oxKFraGsWD](https://user-images.githubusercontent.com/48686795/115765055-9256e900-a3a6-11eb-9421-7a4dcdedb897.gif)

**Comment by thinkingmik** [comment]
Merged
