### ISSUE TITLE
Support for $ref definitions and items: $ref for array definitions

### ISSUE THREAD

**Issue by aaronstaves** [olivierlsc/swagger-express-ts#7]
The current spec specifies that any definition object will be of type "name": [Schema Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#patterned-fields-7).

Looks like there are a handful of fields missing.  The one's I'm specifically interested in are the $ref and items fields that allows for referencing other sub-definitions inside of a definition, as well as referencing what type belongs in an array.

You can see these described in the spec in the [Schema Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#schemaObject) section.

I'll have a PR coming soon for a proposed fix.  Otherwise let me know if there's anything else I could do to help this get pushed.

**Comment by aaronstaves** [comment]
Said PR is here - https://github.com/olivierlsc/swagger-express-ts/pull/8

**Comment by olivierlsc** [comment]
@aaronstaves ,
Are you interested in working together on this bookstore? I can add you as a collaborator.

**Comment by olivierlsc** [comment]
@aaronstaves ,

It's integrated on the developed branch for next tag 1.0.0-beta.2. I close this enhancement.

**Comment by aaronstaves** [comment]
@olivierlsc thanks, but not sure how much time I'd have to contribute.  The project I was working on stopped using inversify so not sure how relevant swagger-express-ts will be for me anymore.

I'd be happy to keep an eye out on things going on with this project though and help out if I can.

**Comment by olivierlsc** [comment]
@aaronstaves thanks for your help. "swagger-express-ts" does not depend on "inversify" to work. "swagger-express-ts" only depends on "expressjs" and "typescript". 
I use" inversify" only as an example.
