### ISSUE TITLE
Endpoints with the same path but with different methods are missing from swagger.json

### ISSUE THREAD

**Issue by czlowiek488** [olivierlsc/swagger-express-ts#75]
If I add two endpoints with the same path but with different method only one is written to settings.json.

I figured out how to fix this issue in installed library.

In `buildSwagger` function replace
`data.paths[controller.path.concat(path.path)] = swaggerPath;`
with
`data.paths[controller.path.concat(path.path)] = {...data.paths[controller.path.concat(path.path)],...swaggerPath};`
and it will work beautifully.

@craigdrabiktxmq @olivierlsc @thinkingmik @lcassiol @moosi @opyate @nathanlepori 
If you could please add it and publish. It is really important for many of us to make it published in npm registry ASAP.

**Comment by thinkingmik** [comment]
Hi, 

I don't find any `data.paths[controller.path.concat(path.path)] = swaggerPath;` line in the code. 
You could open a pull request if you want.

**Comment by czlowiek488** [comment]
@thinkingmik 
Hi,
I found out it in builded package.
This line is what I am talking about.
https://github.com/olivierlsc/swagger-express-ts/blob/ef1fb61ce1359fcc7a9bb47a93cfaf0dca3672b6/lib/swagger-express-ts-lib/src/swagger.service.ts#L297

**Comment by thinkingmik** [comment]
Hi @olivierlsc, 

I have closed some pull requests and issues and created a new version v1.1.1. We would have these new features on `npm`. 
Could you launch `npm run prepare && npm run publish` command with your account when you have some free time?

Thanks.

**Comment by czlowiek488** [comment]
Thank you @thinkingmik however we dont have more time to wait. We will rewrite all swaggers using `tsoa` package. 😢
