### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [olivierlsc/swagger-express-ts#78]
Is this repo still maintained?

**Comment by OhadR** [comment]
i guess not.
the dependencies here are so old... this project is not maintained.

**Comment by mariomurrent-softwaresolutions** [comment]
True, and actually there are enough alternatives already existing

**Comment by OhadR** [comment]
@mariomurrent-softwaresolutions do u have a recommendation for an alternative?

**Comment by mariomurrent-softwaresolutions** [comment]
Well, you can use NestJS which is much easier. But then you need to start from scratch
